/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import db.DB;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.TestPageModel;

/**
 *
 * @author user
 */
public class TestPage extends javax.swing.JFrame {
    Vector data;
    String uname, upass;
    int i=0, score;
    char answers[]={'x','x','x','x','x','x','x','x','x','x'};
    /**
     * Creates new form TestPage
     */
    TestPageModel model;
    public TestPage(int type, String uname, String upass) throws SQLException {
        initComponents();
        this.uname=uname;
        this.upass=upass;
        model=new TestPageModel();
        previous.setVisible(false);
        loadDB(type);
        loadData();
    }
    public void loadDB(int type) throws SQLException
    {
        DB.Connect();
        String sub;
        if(type==0)
            sub="Science";
        else
            sub="Maths";
        String qry="select question, a, b, c, d, answer from question where subject=? order by rand()";
        PreparedStatement smt=DB.conn.prepareStatement(qry);
        smt.setString(1, sub);
        ResultSet rs=smt.executeQuery();
        data=new Vector();
        while(rs.next())
        {
            Vector row=new Vector();
            row.add(rs.getString(1));
            row.add(rs.getString(2));
            row.add(rs.getString(3));
            row.add(rs.getString(4));
            row.add(rs.getString(5));
            row.add(rs.getString(6));
            data.add(row);
        }
        DB.disconnect();
    }
    public void loadData() throws SQLException
    {
       
        //DefaultTableModel model=new DefaultTableModel(data,head);
        //mytable.setModel(model);
        //mytable.setVisible(false);
        ans.requestFocus(true);
        Vector detail=(Vector)data.elementAt(i);
        number.setText("Question "+(i+1));
        qn.setText(detail.elementAt(0).toString());
        a.setText(detail.elementAt(1).toString());
        b.setText(detail.elementAt(2).toString());
        c.setText(detail.elementAt(3).toString());
        d.setText(detail.elementAt(4).toString());
        if(answers[i]=='x')
            ans.setText("");
        else
            ans.setText(""+answers[i]);
    }
    public int check() throws SQLException
    {
        int c;
        score=0;
        for(c=0;c<10;c++)
        {
            Vector detail=(Vector)data.elementAt(c);
            if(answers[c]==detail.elementAt(5).toString().charAt(0))
            {
                score++;
            }
        }
        model.save(uname,upass,(score+""));
        return score;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        qn = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        ans = new javax.swing.JTextField();
        d1 = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        stop = new javax.swing.JButton();
        op_a = new javax.swing.JLabel();
        op_c = new javax.swing.JLabel();
        op_d = new javax.swing.JLabel();
        op_b = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUIZ");

        qn.setBackground(new java.awt.Color(255, 255, 255));
        qn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        qn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        qn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        qn.setOpaque(true);

        a.setBackground(new java.awt.Color(255, 255, 255));
        a.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a.setOpaque(true);

        b.setBackground(new java.awt.Color(255, 255, 255));
        b.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        b.setOpaque(true);

        d.setBackground(new java.awt.Color(255, 255, 255));
        d.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d.setOpaque(true);

        c.setBackground(new java.awt.Color(255, 255, 255));
        c.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c.setOpaque(true);

        next.setBackground(new java.awt.Color(255, 255, 255));
        next.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        next.setForeground(new java.awt.Color(0, 0, 204));
        next.setText("Next");
        next.setToolTipText("Go to next question");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        previous.setBackground(new java.awt.Color(255, 255, 255));
        previous.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        previous.setForeground(new java.awt.Color(0, 0, 204));
        previous.setText("Previous");
        previous.setToolTipText("Go to previous question");
        previous.setHideActionText(true);
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        ans.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ans.setToolTipText("Enter Option as 'a' or 'b' or 'c' or 'd'");

        d1.setBackground(new java.awt.Color(0, 0, 204));
        d1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d1.setForeground(new java.awt.Color(255, 255, 255));
        d1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d1.setText("Enter Option");
        d1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        d1.setOpaque(true);

        number.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        number.setOpaque(true);

        stop.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        stop.setForeground(new java.awt.Color(0, 0, 204));
        stop.setText("Stop Test");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        op_a.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        op_a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op_a.setText("a");
        op_a.setOpaque(true);

        op_c.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        op_c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op_c.setText("c");
        op_c.setOpaque(true);

        op_d.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        op_d.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op_d.setText("d");
        op_d.setOpaque(true);

        op_b.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        op_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op_b.setText("b");
        op_b.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stop)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(op_a, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op_c, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op_d, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op_b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(qn, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ans, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(previous)
                            .addGap(18, 18, 18)
                            .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2))
                        .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(op_a, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op_c, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(op_d, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ans, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        try 
        {
            if(i==0)
                previous.setVisible(false);
            if(i>=0 && i<10)
            {
                i--;
                answers[i]=ans.getText().charAt(0);
                loadData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(TestPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(StringIndexOutOfBoundsException ex)
        {
            JOptionPane.showMessageDialog(null, " ", "Error", 2);
            i++;
        }
    }//GEN-LAST:event_previousActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        try 
        {
            previous.setVisible(true);
            if(i==10)
            {
                int s=check();
                this.dispose();
                new TestResult(s).setVisible(true);
            }
            else
            {
                /*if(Integer.parseInt(ans.getText())==1 || Integer.parseInt(ans.getText())==2 || Integer.parseInt(ans.getText())==3 || Integer.parseInt(ans.getText())==4)
                {
                    JOptionPane.showMessageDialog(null, "Enter options as a or b or c or d", "Error", 2);
                    i--;
                    loadData();
                }*/
                i++;
                answers[i-1]=ans.getText().charAt(0);
                if(i>=0 && i<10)    
                    loadData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(TestPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(StringIndexOutOfBoundsException ex)
        {
            JOptionPane.showMessageDialog(null, " ", "Error", 2);
            i--;
        }
    }//GEN-LAST:event_nextActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        this.dispose();
        new StudDash(uname,upass).setVisible(true);
    }//GEN-LAST:event_stopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TestPage().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JTextField ans;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JLabel number;
    private javax.swing.JLabel op_a;
    private javax.swing.JLabel op_b;
    private javax.swing.JLabel op_c;
    private javax.swing.JLabel op_d;
    private javax.swing.JButton previous;
    private javax.swing.JLabel qn;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
